version: 2
updates:
- package-ecosystem: gradle
  directories:
    - "/"
    - "/java-8"
  schedule:
    interval: daily
    time: "09:00" # 9am UTC
  open-pull-requests-limit: 10
  groups:
    kiota-dependencies:
      patterns:
        - "*kiota*"
- package-ecosystem: gradle
  directory: "/android"
  schedule:
    interval: daily
    time: "10:00" # 10am UTC. After core projects are updated to prevent duplicate PRs
  open-pull-requests-limit: 10
  groups:
    kiota-dependencies:
      patterns:
        - "*kiota*"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    kiota-dependencies:
      patterns:
        - "*kiota*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
