parameters:
- name: task
  type: string
  default: ''

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '**'
    TargetFolder: '$(Agent.BuildDirectory)/Drop/'

- task: Gradle@2
  inputs:
    gradleWrapperFile: '$(Agent.BuildDirectory)/Drop/gradlew'
    workingDirectory: '$(Agent.BuildDirectory)/Drop/'
    options: '-x jar -x javadoc -x javadocJar -x compileJava -x processResources -x classes -x sourceJar'
    tasks: ${{ parameters.task }}
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false