steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '**'
    TargetFolder: '$(System.DefaultWorkingDirectory)/_msgraph-sdk-java build and packaging/drop/'

- task: Gradle@2
  inputs:
    gradleWrapperFile: '$(System.DefaultWorkingDirectory)/_msgraph-sdk-java build and packaging/drop/gradlew'
    workingDirectory: '$(System.DefaultWorkingDirectory)/_msgraph-sdk-java build and packaging/drop/'
    options: '-x jar -x javadoc -x javadocJar -x compileJava -x processResources -x classes -x sourceJar'
    tasks: 'publishMavenCentralReleasePublicationToSonatypeRepository'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false