name: "Checks the SDK only using APIs from the targeted API level"

on:
  workflow_dispatch:
  push:
    branches: [main, support/5.x.x]
  pull_request:
    branches: [main, support/5.x.x]

jobs:
  lint-api-level:
    runs-on: [self-hosted, 1ES.Pool=1es-ubuntu-msgraph-sdk-java-memory-latest-m]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.1
      - name: Add execution right to the script
        run: chmod +x gradlew
        working-directory: ./android
      - name: Build SDK with Android project configuration
        id: lint
        run: ./gradlew --no-daemon build
        working-directory: ./android
      - name: Upload linting results
        if: failure() && steps.lint.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: ./android/build/reports
