name: "Checks the SDK only using APIs from the targeted API level"

on: 
  workflow_dispatch:
  push:
    branches:
      - dev
      - feature/6.0
  pull_request:
    branches:
      - dev
      - feature/6.0

jobs:
  lint-api-level:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 18
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.9
      - name: Add execution right to the script
        run: chmod +x gradlew
        working-directory: ./android
      - name: Build SDK with Android project configuration
        id: lint
        run: ./gradlew --no-daemon build
        working-directory: ./android
      - name: Upload linting results
        if: failure() && steps.lint.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: ./android/build/reports
